name: Snake

on:
  schedule:
    - cron: '* */6 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Job to update my snake food
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ohenrydevopr
          svg_out_path: public/github/snake.svg
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: snake
          build_dir: public/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
